# https://kubernetes.io/docs/concepts/configuration/configmap/
apiVersion: v1
kind: ConfigMap
metadata:
  name: csv-import-config
data:
  GE_PLUGIN_SLUG: tbz-csv
  GE_CSV_HEADERS: "Gebiet,Straße,BaumNr.,Gattung/Art,Hochwert,Rechtswert,Pflanzjahr"
  GE_CSV_USED_EPSG: "EPSG:31467"
  GE_CSV_TO_EPSG: "EPSG:4236"

  GE_HOST_PATH: http://backend
  GE_PLUGIN_PATH: http://csv-import
  GE_CLIENT_ID: tbz-csv-import-plugin

