apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- configmap.yaml
images:
- name: plugin-image
  newName: ghcr.io/green-ecolution/tbz-csv-import-plugin
  newTag: d3ebf53
generators:
- ./secret-generator.yaml
