#ENC[AES256_GCM,data:EPF10UICv2E719DaoghcRK8kK1HqXHABw5Ag/76RoIa3UrTCNogknB/37OgsmkDbx89D7JPg5W7nkw==,iv:5zd7zZZLJlVVcy7lzT/mm5h0iOU76eriUvNg5nGgwIk=,tag:Xi1xgTeHRZckOV5PSxW48Q==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: csv-import-secret
type: Opaque
data:
    GE_CLIENT_SECRET: ENC[AES256_GCM,data:ds7/hdlWgn1I/5kmqLs9LYCQSDsoHuTLJ4vGZoyLoqYDY8lMwv0NJbplM18=,iv:u2aoI+UxReCkbtyKur0f3S8xpjV7+AeF8OuD+hdV8CA=,tag:RkFJ1vRnnFRNk93jnXJ1Xg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Tlh2Wnd2VTdCanJ4dzNa
            Zk5DTnZjRnFmTkFVZXA4TXZhenZxOGJkM21RCmNQRHlvdSs0c3pBYzkvSDBjUXkr
            djBSdEF2TnZqdmVKN29TcUUzdmJXcVkKLS0tIGFBMEsyK0J5SjBjOTAwY0lKb0VK
            bXRsRUpvREZQRGdZTlF0TmJGOStWZGsKLDXpgLoD9vKN0uUpb16+h+958USxnmVW
            YuQLYiOdiegFmcd5PJ5PzByA0t3jjv1iTJCN/udrMRBQTLDpaVCC3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-30T20:58:31Z"
    mac: ENC[AES256_GCM,data:UqBPPKVG98zgMK8w/iGngVoXIg63xv1/iYF9TthKW/00I4biozOlUAxVpMy38vQ+u9WyoVsa4G+Rh522Fu6BOR91LYxK9PeZn7Bo1+91In0fwxZLXO5prBofCIMb72wHuloWeW4xCOuZHhDva2M6kGPvtplmAQtNN/067+pTxPU=,iv:yb0fnVNJShLue/5rNnkQ20SWdQXJKIORiZtPbSVt6eI=,tag:kMNmhQbXD5V7l+IDmbH74Q==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.4
